[features]
seeds = false
skip-lint = false
[programs.localnet]
first = "3fg4A32dEzRjuh9fEgrXWYqhi2Xy8RdYn5SWH2eNso8v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/kunal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
